### ISSUE TITLE
Error when trying to add observed data defined in mass concentration to `PIOutputMapping` with output in molar concentration

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.ParameterIdentification#87]
When adding a data set with observed data defined in mass concentration (e.g., µg/dl) to a `PIOutputMapping` with a quantity in molar concentration (e.g., µmol/l), and the observed data does not have molecular weight defined, an error is thrown:

```
# Load simulation
sim_250mg <- loadSimulation(system.file("extdata", "Aciclovir.pkml", package = "ospsuite"))

# Load data
filePath <- system.file("extdata", "Aciclovir_Profiles.xlsx", package = "ospsuite.parameteridentification")

# Create importer configuration for the file
importConfig <- createImporterConfigurationForFile(filePath = filePath)
# Set naming patter
importConfig$namingPattern <- "{Source}.{Sheet}.{Dose}"
# Import data sets
obsData <- loadDataSetsFromExcel(xlsFilePath = filePath, importerConfigurationOrPath = importConfig, importAllSheets = TRUE)

# Create PIOutputMapping for output of molar concentration
simOutputPath <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
outputMapping_250mg <- PIOutputMapping$new(quantity = getQuantity(path = simOutputPath, container = sim_250mg))

# Try to add observed data
outputMapping_250mg$addObservedDataSets(obsData$`Aciclovir_Profiles.Vergin 1995.Iv.250 mg`)
```

Error:

```
> outputMapping_250mg$addObservedDataSets(obsData$`Aciclovir_Profiles.Vergin 1995.Iv.250 mg`)
Error in rClr::clrCall(dimensionTask, "ConvertToBaseUnit", dimension,  : 
  Type:    OSPSuite.Core.Domain.UnitSystem.UnableToResolveParametersException
Message: Unable to convert to mg/l.
Molecular Weight not available.
Method:  Double UnitValueToBaseUnitValue(OSPSuite.Core.Domain.UnitSystem.Unit, Double)
Stack trace:
   at OSPSuite.Core.Domain.UnitSystem.MergedDimensionFor`1.UnitValueToBaseUnitValue(Unit unit, Double valueInUnit)
   at OSPSuite.Core.Domain.UnitSystem.DimensionExtensions.<>c__DisplayClass5_0.<UnitValuesToBaseUnitValues>b__0(Double value)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OSPSuite.Core.Domain.UnitSystem.DimensionExtensions.UnitValuesToBaseUnitValues(IDimension dimension, Unit unit, IEnumerable`1 values)
   at OSPSuite.R.Services.DimensionTask.convertToBaseUnit(IDimension dimension, String displayUnit, Nullable`1 molWeight, Double[] valuesInDisplayUnit)
   at OSPSuite.R.Service
```

Happens here:

https://github.com/Open-Systems-Pharmacology/OSPSuite.ParameterIdentification/blob/9b33b4a941ca27db877499acf8aff7470b28df9a/R/PIOutputMapping.R#L97-L112

Suggestion: the current implementation checks if observed data values can be converted to the units of simulated quantity and throws an error if it fails. This should be changed to - try to convert observed data, if it fails - try to convert the unit of simulated quantity to the unit of observed data, using the molecular weight that can be retrieved:

`sim_500mg$molWeightFor(simOutputPath)`

or, in  `PIOutputMapping` it would be

`quantity$simulation$molWeightFor(simOutputPath)`

but only once https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1356 is implemented.

**Comment by rengelke** [comment]
@PavelBal 
Extraction of mol. weight from `quantity` as a fallback when observed data lacks it might not be feasible, as the parent container is not accessible (at least from what I understand).

A possible solution could be refactoring the PIOutputMapping constructor to:
```
PIOutputMapping$new(path = x, container = y)
```

This would allow retrieving the `quantity` and mol. weight directly within `PIOutputMapping`:
```
getQuantity(path = x, container = y)
y$molWeightFor(x)
```

**Comment by PavelBal** [comment]
@rengelke Let's see if this can be implemented quickly: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1356

Then you can get the simulation object of the `Quantity` and call `quantity$simulation$molWeightFor(simOutputPath)`.


And you mean
`PIOutputMapping$new(path = x, simulation = y)`?

Because not every container is a simulation, but you can only get the mol weight from the simulation object.

**Comment by rengelke** [comment]
> `PIOutputMapping$new(path = x, simulation = y)`?

Yes, I am talking about the simulation as this is the only way to get the mol. weight. 

Then I wait on this one

**Comment by rwmcintosh** [comment]
You can get the molecular weight from the quantity using the container task

From the entity -> RootContainer -> Molecule -> parameter -> Value
